services:
  zeno-mysql-db:
    image: mariadb:12.0.2-noble
    container_name: zeno-mysql-db
    restart: always
    
    # Environment variables for configuration
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    ports:
      - "3306:3306"
      
    # Use a named volume for data persistence
    volumes:
      - zeno-eats-data:/var/lib/mysql

volumes:
  zeno-eats-data:

networks:
  zeno-eats-network:
